### ISSUE TITLE
put method is vague

### ISSUE THREAD

**Issue by ghost** [dorothysyu/part2#10]
// Checks that the given object is the same type as already-existing type.
    // If it is, puts the obj at the ith index. Replaces the object
    // that was already there if it exists.
    void put(int i, Object* obj) {

If my array looks like:
[0, 1, 2]

s = new String("Something")

How would this function handles the cases put(-1, s), put(3, s), put(10, s)?

I assume that -1 does nothing, 3 appends to the end and 10 does nothing.

**Comment by dorothysyu** [comment]
~This would be accurate. Will update the spec to match that.~ Actually, scratch that, sorry! This would do nothing if the index was out of bounds. So -1, 3, and 10 would do nothing. This method would only work for indexes that already exist in the array.

**Comment by dorothysyu** [comment]
pushed
