### ISSUE TITLE
Tests need to call Google Test framework

### ISSUE THREAD

**Issue by gyroknight** [dorothysyu/part2#15]
Please consult the example file in Piazza [@338](https://piazza.com/class/k51bluky59n2jr?cid=338) and the [Google Test Primer](https://github.com/google/googletest/blob/master/googletest/docs/primer.md) to see how to run your tests.

**Comment by dorothysyu** [comment]
I just did it! Let me know if it works - I can't try it out to see because I don't have definitions for the methods

**Comment by gyroknight** [comment]
The tests seem to have some issues, but the Google Test part seems to work correctly.
