### ISSUE TITLE
length of Arrays are vague

### ISSUE THREAD

**Issue by ghost** [dorothysyu/part2#16]
The length should be the number of elements in the array, not the current capacity of it. When you initialize it with a length, it is empty. The length is there as an internal optimization for preallocating space.
    // Returns the length of the array.
    int get_length() { return this->num_elements; }

void testArrayCreation() {
    Array* a1 = new Array(5);
    Array* a2 = new Array(10);
    CS4500_ASSERT_TRUE(a1->get_length()==5);
    CS4500_ASSERT_TRUE(a2->get_length()==10);
    exit(0);
}

**Comment by dorothysyu** [comment]
You're right - length should be number of elements in array, not capacity. Just pushed this change
