### ISSUE TITLE
Misuse of String::String(const char*)

### ISSUE THREAD

**Issue by gyroknight** [dorothysyu/part2#17]
On lines 51 and 52, you pass in `new char[1]` and `new char[2]`, however, that constructor is supposed to create a `String` that represents a null-terminated string in `const char*` form. By passing in those arrays, you have no guarantee that the initialization value is actually a string, nor can the user (or developer) tell if those are statically allocated string or dynamically allocated ones that should be freed.

**Comment by dorothysyu** [comment]
Sorry about that - that must've been a leftover test from an old version of a String constructor that would've taken in a character array. Just pushed these changes
