### ISSUE TITLE
Add tests for new datatypes

### ISSUE THREAD

**Issue by gyroknight** [dorothysyu/part2#3]
Please update your tests to include coverage for `int`, `float`, and `bool` arrays.

**Comment by dorothysyu** [comment]
Working on it now

**Comment by ghost** [comment]
Since CwC disallows macros and templates, consider making the array of void* (or references) and passing in a pointer (e.g., int*, float*, Object *)

**Comment by dorothysyu** [comment]
As per [this](https://piazza.com/class/k51bluky59n2jr?cid=369) and [this](https://piazza.com/class/k51bluky59n2jr?cid=331) Piazza post, we decided to use multiple Array classes to be able to support different data types. We did not want to box primitives and wanted to avoid making the user cast to their desired data types.
