### ISSUE TITLE
Use common string.h and object.h

### ISSUE THREAD

**Issue by MHebes** [dorothysyu/part2#6]
Based on piazza, and to keep things consistent with the other repos, I recommend we use a consistent object.h and string.h interface with the rest of the class.

https://github.com/chasebish/cwc_object_string

Let me know what you think. Tests will need to be updated as well.

**Comment by dorothysyu** [comment]
We agree - we can also adopt this API. Will work on that now

**Comment by dorothysyu** [comment]
pushed !
