### ISSUE TITLE
fill method is vague

### ISSUE THREAD

**Issue by ghost** [dorothysyu/part2#7]
// Fills the array with the given value if the type of the object matches
    // the already existing type.
    void fill(Object* val);

Define the behavior when the array is empty, partially filled and full compared to the initial length passed. Does this also make deep copies of the object?

**Comment by dorothysyu** [comment]
This should've been the signature - "Sets val as the value for all the elements in the array object." So it would do nothing for an empty array, and if it's partially filled/full, replace already-existing values with. I can update the spec to be more specific. This would make deep copies of the object
