### ISSUE TITLE
Passing in a char * type is not a good way to make your container generic

### ISSUE THREAD

**Issue by ghost** [dorothysyu/part2#8]
// Checks that the given object is the same type as already-existing type.
    // If it is, puts the obj at the ith index. Replaces the object
    // that was already there if it exists.
    void put(int i, Object* obj);

Array(const char* type, int length)

Passing in a char * type and asking to check if it is the same type with an Object * is not smart. If the only pointer type you return is an Object * then just assume everything is an Object * and wrap the primitives. Or go the c generic way and make it a void**.

My advise is to just assume it is a Object *.

**Comment by dorothysyu** [comment]
This is a good observation and we've addressed this by getting rid of that entirely. We now have different subclasses of Arrays for each data type - these changes have been pushed
